apiVersion: 1

datasources:
  - name: B3Quotes
    type: influxdb
    access: proxy
    url: ${INFLUXDB_URL}
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    jsonData:
      version: Flux
      organization: b3loader
      defaultBucket: quote_events
      tlsSkipVerify: true