services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
    ports:
      - "${INFLUXDB_PORT}:${INFLUXDB_PORT}"
    volumes:
      - ./data/influxdb-data:/var/lib/influxdb2
    env_file:
      - path: ./.env
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: "1000:1000"
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    volumes:
      - ./data/grafana-data:/var/lib/grafana:rw
      - ./deployments/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=${GRAFANA_HOME_DASHBOARD}
    env_file:
      - path: ./.env
  b3loader:
    build:
      dockerfile: api/build/Dockerfile
    container_name: b3loader
    depends_on:
      - influxdb
    environment:
      INFLUXDB_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      ENVIRONMENT: ${ENVIRONMENT}
      DIRECTORY_PATH: ${B3LOADER_DIRECTORY_PATH}
      B3LOADER_PORT: ${B3LOADER_PORT}
    volumes:
      - ./data/b3loader-data:${B3LOADER_DIRECTORY_PATH}
    ports:
      - "${B3LOADER_PORT}:${B3LOADER_PORT}"
    env_file:
      - path: ./.env
  b3loader-front:
    container_name: b3loader-front
    depends_on:
      - b3loader
    build:
      context: ./frontend
      dockerfile: build/Dockerfile
    ports:
      - 9000:80
    environment:
      VITE_B3LOADER_URL: ${B3LOADER_URL}
      VITE_DIRECTORY_PATH: ${B3LOADER_DIRECTORY_PATH}
    volumes:
      - ./data/b3loader-data:${B3LOADER_DIRECTORY_PATH}
    env_file:
      - path: ./.env
