services:
  b3loader:
    image: b3loader
    container_name: b3loader
    environment:
      INFLUXDB_TOKEN: "influxdb"
      INFLUXDB_URL: "http://influxdb:8086"
      INFLUXDB_ORG: "b3loader"
      INFLUXDB_BUCKET: "quote_events"
      ENVIRONMENT: "dev"
      DIRECTORY_PATH: "/mnt/data"
    volumes:
      - ./data/b3loader-data:/mnt/data
    ports:
      - "8080:8080"
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "influxdb"
      DOCKER_INFLUXDB_INIT_PASSWORD: "influxdb"
      DOCKER_INFLUXDB_INIT_ORG: "b3loader"
      DOCKER_INFLUXDB_INIT_BUCKET: "quote_events"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "influxdb"
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb-data:/var/lib/influxdb2
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: "1000:1000"
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana-data:/var/lib/grafana
      - ./deployments/grafana:/etc/grafana:ro
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=grafana
