services:
  b3loader:
    image: b3loader:latest
    container_name: b3loader
    environment:
      INFLUXDB_TOKEN: "influxdb"
      INFLUXDB_URL: "http://influxdb:8086"
      INFLUXDB_ORG: "b3loader"
      INFLUXDB_BUCKET: "quote_events"
      ENVIRONMENT: "dev"
      DIRECTORY_PATH: "/mnt/data"
    volumes:
      - ./data/b3loader-data:/mnt/data
    ports:
      - "8080:8080"
  influxdb:
    image: influxdb:2.0.7
    container_name: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "influxdb"
      DOCKER_INFLUXDB_INIT_PASSWORD: "influxdb"
      DOCKER_INFLUXDB_INIT_ORG: "b3loader"
      DOCKER_INFLUXDB_INIT_BUCKET: "quote_events"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "influxdb"
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "$UID:$GID"
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana-data:/var/lib/grafana
