{
 "title": "B3 Stock Value",
 "time": { "from": "2017-12-31T23:00:00.000Z", "to": "2023-12-31T22:59:59.000Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BBAS3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "query": "from(bucket: \"quote_events\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_quote\")\n  |> filter(fn: (r) => r[\"StockName\"] == \"BBAS3\")\n  |> filter(fn: (r) => r[\"_field\"] == \"LastPrice\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "KNCR11",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "query": "from(bucket: \"quote_events\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_quote\")\n  |> filter(fn: (r) => r[\"StockName\"] == \"KNCR11\")\n  |> filter(fn: (r) => r[\"_field\"] == \"LastPrice\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "XPLG11",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "query": "from(bucket: \"quote_events\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_quote\")\n  |> filter(fn: (r) => r[\"StockName\"] == \"XPLG11\")\n  |> filter(fn: (r) => r[\"_field\"] == \"LastPrice\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "TAEE11",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "query": "from(bucket: \"quote_events\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_quote\")\n  |> filter(fn: (r) => r[\"StockName\"] == \"TAEE11\")\n  |> filter(fn: (r) => r[\"_field\"] == \"LastPrice\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}